---

- hosts: localhost
  vars_files:
   - key.yml
  vars:
   bucket_name: clouddnuts002
  tasks:
   - name: S3 create bucket
     s3:
       aws_access_key: "{{ accesskey}}" 
       aws_secret_key: "{{ secretkey}}"
       bucket: "{{ bucket_name}}"
       mode: create
