---

- hosts: localhost
  vars_files: 
   - key.yml
  vars: 
   bucketname: clouddnuts001
  tasks:
   - name: put object
     s3:
      aws_access_key: "{{accesskey }}"
      aws_secret_key: "{{secretkey }}"
      bucket: "{{ bucketname}}"
      object: test.txt
      src: test.txt
      mode: put

 
