- hosts: localhost
  vars_files:
   - key.yml
  vars:
   bucket_name: clouddnuts-test001
  tasks:
  # - name: S3 create bucket
  #   s3:
  #     aws_access_key: "{{ accesskey}}" 
  #     aws_secret_key: "{{ secretkey}}"
  #     bucket: "{{ bucket_name}}"
  #     mode: create
  #   tags:
  #     - create


   - name: Create S3 bucket
     command: >
      aws s3api create-bucket
     # --region {{ region }}
       --bucket " {{ bucket_name }}"
     # {% if  region != "us-east-1" %}
     # --create-bucket-configuration LocationConstraint={{ region }}
     # {% endif %}
    #environment: "{{ environment_vars }}"
     register: s3
     failed_when: "s3.stderr != '' and 'An error occurred' in s3.stderr and 'BucketAlreadyExists' not in s3.stderr"
